### ISSUE TITLE
#[napi]宏和#[no_mangle]宏是否冲突？

### ISSUE THREAD

**Issue by xujingguo58** [ohos-rs/ohos-rs#111]
在rust项目中，如果只有#[napi]，则在ets里可以正常调用到，如果在任意文件中使用了#[no_mangle]pub extern "C" fn导出C函数，则在ets中无法调用到，提示：
SyntaxError: the requested module 'xxxx' does not provide an export name 'initial' which imported by xxxx

**Comment by richerfu** [comment]
请给一个复现的示例。

**Comment by xujingguo58** [comment]
@richerfu 
1. 在文件1中定义了：
```
#[napi]
pub fn initial() -> Result<()>
```
2. 在文件2中定义了：
```
#[no_mangle]
pub extern "C" fn stream_client_connect(
```
编译的时候如果不包含文件2，则生成的so 是可以正常调用的
如果包含了，则生成的so在ets里无法调用，提示：
`SyntaxError: the requested module 'xxxx' does not provide an export name 'initial' which imported by xxxx`

**Comment by richerfu** [comment]
```rust
use napi_derive_ohos::napi;

#[napi]
pub fn add(left: u32, right: u32) -> u32 {
  left + right
}


#[no_mangle]
pub extern "C" fn stream_client_connect() {}
```
调用 add 似乎没问题，你是要在 ets 调用 stream_client_connect？

**Comment by xujingguo58** [comment]
我刚才用排除法定位了一下，不是必现的，其他所有的函数都没有问题，只有这个函数：
```
#[no_mangle]
pub unsafe extern "C" fn destroy_sink_manager(manager_ptr: *mut c_void) {
    let mut manager = unsafe { Box::from_raw(manager_ptr.cast::<CSinkManager>()) };
    get_runtime().block_on(manager.sink_manager.release());
    drop(manager);
}
```
这个函数只要加了#[no_mangle]，就找不到方法，如果把宏注释掉，就没有问题

我是想在一个rust库里，同时到处给ets使用的方法和C++ 使用的方法，destroy_sink_manager在NDK中的C++文件中调用

**Comment by richerfu** [comment]
应该是跟系统某个方法冲突重名了。建议先改名字。

**Comment by xujingguo58** [comment]
> 这里有两个解决方案：
> 
> 1. 直接改名字
> 2. 配置成条件构建
>    ```rust
>    #[cfg(not(target_env = "ohos"))]
>    #[no_mangle]
>      pub unsafe extern "C" fn destroy_sink_manager(manager_ptr: *mut c_void) {
>          let mut manager = unsafe { Box::from_raw(manager_ptr.cast::<CSinkManager>()) };
>          get_runtime().block_on(manager.sink_manager.release());
>          drop(manager);
>      }
>    ```

**Comment by richerfu** [comment]
> @richerfu 
> 还有个问题想请教下，使用rust编译出来的so，是否可以同时给ets和native使用？
> 现在的场景是在原有项目上，单独新增部分#[napi] API用于ets直接调用，原有部分C API直接复用，直接导出用于在NDK C++代码中调用，两套API在同一个API中，现在如果是在NDK中引入了prebuild 的so，ets中调用就会报错，如果不引用就没有问题

建议把napi的部分拆成独立的一个动态库，跟c的部分独立出来。napi会涉及到大量的胶水代码，只是宏把这部分对开发者隐藏了。不确保两者完全没有影响
